[features]

	[feature.his_SEX]
	type = "categorical"
	num_categories = 99

	[feature.his_HISPANIC]
	type = "categorical"
	num_categories = 99

	[feature.his_PRIMLANG]
	type = "categorical"
	num_categories = 99

	[feature.his_EDUC]
	type = "numerical"
	shape = [1]

	[feature.his_MARISTAT]
	type = "categorical"
	num_categories = 99

	[feature.his_RESIDENC]
	type = "categorical"
	num_categories = 99

	[feature.his_HANDED]
	type = "categorical"
	num_categories = 99

	[feature.his_NACCNIHR]
	type = "categorical"
	num_categories = 99

	[feature.his_NACCAGE]
	type = "numerical"
	shape = [1]

	[feature.his_NACCMOM]
	type = "categorical"
	num_categories = 99

	[feature.his_NACCDAD]
	type = "categorical"
	num_categories = 99

	[feature.ph_HEIGHT]
	type = "numerical"
	shape = [1]

	[feature.ph_WEIGHT]
	type = "numerical"
	shape = [1]

	[feature.ph_BPSYS]
	type = "numerical"
	shape = [1]

	[feature.ph_BPDIAS]
	type = "numerical"
	shape = [1]

	[feature.ph_HRATE]
	type = "numerical"
	shape = [1]

	[feature.npiq_DEL]
	type = "categorical"
	num_categories = 99

	[feature.npiq_HALL]
	type = "categorical"
	num_categories = 99

	[feature.npiq_AGIT]
	type = "categorical"
	num_categories = 99

	[feature.npiq_DEPD]
	type = "categorical"
	num_categories = 99

	[feature.npiq_ANX]
	type = "categorical"
	num_categories = 99

	[feature.npiq_ELAT]
	type = "categorical"
	num_categories = 99

	[feature.npiq_APA]
	type = "categorical"
	num_categories = 99

	[feature.npiq_DISN]
	type = "categorical"
	num_categories = 99

	[feature.npiq_IRR]
	type = "categorical"
	num_categories = 99

	[feature.npiq_MOT]
	type = "categorical"
	num_categories = 99

	[feature.npiq_NITE]
	type = "categorical"
	num_categories = 99

	[feature.npiq_APP]
	type = "categorical"
	num_categories = 99

	[feature.npiq_NPISCORE]
	type = "numerical"
	shape = [1]

	[feature.gds_SATIS]
	type = "categorical"
	num_categories = 99

	[feature.gds_DROPACT]
	type = "categorical"
	num_categories = 99

	[feature.gds_EMPTY]
	type = "categorical"
	num_categories = 99

	[feature.gds_BORED]
	type = "categorical"
	num_categories = 99

	[feature.gds_SPIRITS]
	type = "categorical"
	num_categories = 99

	[feature.gds_AFRAID]
	type = "categorical"
	num_categories = 99

	[feature.gds_HAPPY]
	type = "categorical"
	num_categories = 99

	[feature.gds_HELPLESS]
	type = "categorical"
	num_categories = 99

	[feature.gds_STAYHOME]
	type = "categorical"
	num_categories = 99

	[feature.gds_MEMPROB]
	type = "categorical"
	num_categories = 99

	[feature.gds_WONDRFUL]
	type = "categorical"
	num_categories = 99

	[feature.gds_WRTHLESS]
	type = "categorical"
	num_categories = 99

	[feature.gds_ENERGY]
	type = "categorical"
	num_categories = 99

	[feature.gds_HOPELESS]
	type = "categorical"
	num_categories = 99

	[feature.gds_BETTER]
	type = "categorical"
	num_categories = 99

	[feature.gds_NACCGDS]
	type = "numerical"
	shape = [1]

	[feature.faq_BILLS]
	type = "categorical"
	num_categories = 99

	[feature.faq_TAXES]
	type = "categorical"
	num_categories = 99

	[feature.faq_SHOPPING]
	type = "categorical"
	num_categories = 99

	[feature.faq_GAMES]
	type = "categorical"
	num_categories = 99

	[feature.faq_STOVE]
	type = "categorical"
	num_categories = 99

	[feature.faq_MEALPREP]
	type = "categorical"
	num_categories = 99

	[feature.faq_EVENTS]
	type = "categorical"
	num_categories = 99

	[feature.faq_PAYATTN]
	type = "categorical"
	num_categories = 99

	[feature.faq_REMDATES]
	type = "categorical"
	num_categories = 99

	[feature.faq_TRAVEL]
	type = "categorical"
	num_categories = 99

	[feature.faq_FAQTOTAL]
	type = "numerical"
	shape = [1]

	[feature.bat_MMSEORDA]
	type = "numerical"
	shape = [1]

	[feature.bat_MMSEORLO]
	type = "numerical"
	shape = [1]

	[feature.bat_NACCMMSE]
	type = "numerical"
	shape = [1]

	[feature.bat_NACCMOCA]
	type = "numerical"
	shape = [1]

	[feature.bat_MOCATRAI]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCACUBE]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCACLOC]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCACLON]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCACLOH]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCANAMI]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCADIGI]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCALETT]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCASER7]
	type = "numerical"
	shape = [1]

	[feature.bat_MOCAREPE]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCAFLUE]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCAABST]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCARECN]
	type = "numerical"
	shape = [1]

	[feature.bat_MOCAORDT]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCAORMO]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCAORYR]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCAORDY]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCAORPL]
	type = "categorical"
	num_categories = 99

	[feature.bat_MOCAORCT]
	type = "categorical"
	num_categories = 99

	[feature.cd_DIAGNOSIS]
	type = "categorical"
	num_categories = 99

	[feature.cdr_MEMORY]
	type = "numerical"
	shape = [1]

	[feature.cdr_ORIENT]
	type = "numerical"
	shape = [1]

	[feature.cdr_JUDGEMENT]
	type = "numerical"
	shape = [1]

	[feature.cdr_COMMUN]
	type = "numerical"
	shape = [1]

	[feature.cdr_HOMEHOBB]
	type = "numerical"
	shape = [1]

	[feature.cdr_PERSCARE]
	type = "numerical"
	shape = [1]

	[feature.cdr_CDRSUM]
	type = "numerical"
	shape = [1]

	[feature.cdr_CDRGLOB]
	type = "numerical"
	shape = [1]

	[feature.FS_MTL_VOLUME]
	type = "numerical"
	shape = [1]

	[feature.FS_NEO-T_VOLUME]
	type = "numerical"
	shape = [1]

	[feature.FS_TEMPO_PARIETAL_VOLUME]
	type = "numerical"
	shape = [1]

	[feature.FS_FRONTAL_VOLUME]
	type = "numerical"
	shape = [1]

	[feature.iha_Psychiatric]
	type = "categorical"
	num_categories = 99

	[feature.iha_Neurologic]
	type = "categorical"
	num_categories = 99

	[feature.iha_Cardiovascular]
	type = "categorical"
	num_categories = 99

	[feature.iha_Endocrine_Metabolic]
	type = "categorical"
	num_categories = 99

	[feature.iha_Musculoskeletal]
	type = "categorical"
	num_categories = 99

	[feature.iha_Smoking_Alcohol_Drug_Use]
	type = "categorical"
	num_categories = 99

[labels]

	[label.amy_label]
	type = "categorical"
	num_categories = 2

	[label.tau_label]
	type = "categorical"
	num_categories = 2

