[features]

	[feature.DIAGNOSIS]
	type = "categorical"
	num_categories = 4

	[feature.AGE_MRI]
	type = "numerical"
	shape = [1]

	[feature.PTGENDER]
	type = "categorical"
	num_categories = 3

	[feature.PTEDUCAT]
	type = "numerical"
	shape = [1]

	[feature.PTTLANG]
	type = "categorical"
	num_categories = 3

	[feature.PTETHCAT]
	type = "categorical"
	num_categories = 4

	[feature.PTRACCAT]
	type = "categorical"
	num_categories = 8

	[feature.AMY_SUVR]
	type = "numerical"
	shape = [1]

	[feature.MTL_SUVR]
	type = "numerical"
	shape = [1]

	[feature.NEO-T_SUVR]
	type = "numerical"
	shape = [1]

	[feature.MMSCORE]
	type = "numerical"
	shape = [1]

	[feature.CDGLOBAL]
	type = "numerical"
	shape = [1]

	[feature.VSBPSYS]
	type = "numerical"
	shape = [1]

	[feature.VSBPDIA]
	type = "numerical"
	shape = [1]

	[feature.VSPULSE]
	type = "numerical"
	shape = [1]

	[feature.VSRESP]
	type = "numerical"
	shape = [1]

[labels]

	[label.amy_label]
	type = "categorical"
	num_categories = 2

	[label.tau_label]
	type = "categorical"
	num_categories = 2

