[features]

	[feature.his_SEX]
	type = "categorical"
	num_categories = 2

	[feature.his_HISPANIC]
	type = "categorical"
	num_categories = 2

	[feature.his_EDUC]
	type = "numerical"
	shape = [1]

	[feature.his_MARISTAT]
	type = "categorical"
	num_categories = 6

	[feature.his_LIVSIT]
	type = "categorical"
	num_categories = 5

	[feature.his_INDEPEND]
	type = "categorical"
	num_categories = 4

	[feature.his_RESIDENC]
	type = "categorical"
	num_categories = 4

	[feature.his_HANDED]
	type = "categorical"
	num_categories = 3

	[feature.his_NACCAGE]
	type = "numerical"
	shape = [1]

	[feature.his_NACCNIHR]
	type = "categorical"
	num_categories = 6

	[feature.his_NACCMOM]
	type = "categorical"
	num_categories = 2

	[feature.his_NACCDAD]
	type = "categorical"
	num_categories = 2

	[feature.his_TOBAC30]
	type = "categorical"
	num_categories = 2

	[feature.his_TOBAC100]
	type = "categorical"
	num_categories = 2

	[feature.his_SMOKYRS]
	type = "numerical"
	shape = [1]

	[feature.his_PACKSPER]
	type = "numerical"
	shape = [1]

	[feature.his_QUITSMOK]
	type = "numerical"
	shape = [1]

	[feature.his_CVHATT]
	type = "categorical"
	num_categories = 3

	[feature.his_CVAFIB]
	type = "categorical"
	num_categories = 3

	[feature.his_CVANGIO]
	type = "categorical"
	num_categories = 3

	[feature.his_CVBYPASS]
	type = "categorical"
	num_categories = 3

	[feature.his_CVPACE]
	type = "categorical"
	num_categories = 3

	[feature.his_CVCHF]
	type = "categorical"
	num_categories = 3

	[feature.his_CVOTHR]
	type = "categorical"
	num_categories = 3

	[feature.his_CBSTROKE]
	type = "categorical"
	num_categories = 3

	[feature.his_CBTIA]
	type = "categorical"
	num_categories = 3

	[feature.his_PD]
	type = "categorical"
	num_categories = 2

	[feature.his_PDOTHR]
	type = "categorical"
	num_categories = 2

	[feature.his_SEIZURES]
	type = "categorical"
	num_categories = 3

	[feature.his_NCOTHR]
	type = "categorical"
	num_categories = 3

	[feature.his_DIABETES]
	type = "categorical"
	num_categories = 3

	[feature.his_HYPERTEN]
	type = "categorical"
	num_categories = 3

	[feature.his_HYPERCHO]
	type = "categorical"
	num_categories = 3

	[feature.his_B12DEF]
	type = "categorical"
	num_categories = 3

	[feature.his_THYROID]
	type = "categorical"
	num_categories = 3

	[feature.his_INCONTU]
	type = "categorical"
	num_categories = 3

	[feature.his_INCONTF]
	type = "categorical"
	num_categories = 3

	[feature.his_ALCOHOL]
	type = "categorical"
	num_categories = 3

	[feature.his_ABUSOTHR]
	type = "categorical"
	num_categories = 3

	[feature.his_PSYCDIS]
	type = "categorical"
	num_categories = 3

	[feature.ph_HEIGHT]
	type = "numerical"
	shape = [1]

	[feature.ph_WEIGHT]
	type = "numerical"
	shape = [1]

	[feature.ph_BPSYS]
	type = "numerical"
	shape = [1]

	[feature.ph_BPDIAS]
	type = "numerical"
	shape = [1]

	[feature.ph_HRATE]
	type = "numerical"
	shape = [1]

	[feature.ph_VISION]
	type = "numerical"
	shape = [1]

	[feature.ph_VISCORR]
	type = "numerical"
	shape = [1]

	[feature.ph_VISWCORR]
	type = "numerical"
	shape = [1]

	[feature.ph_HEARING]
	type = "numerical"
	shape = [1]

	[feature.ph_HEARAID]
	type = "numerical"
	shape = [1]

	[feature.ph_HEARWAID]
	type = "numerical"
	shape = [1]

	[feature.cvd_ABRUPT]
	type = "categorical"
	num_categories = 2

	[feature.cvd_STEPWISE]
	type = "categorical"
	num_categories = 2

	[feature.cvd_SOMATIC]
	type = "categorical"
	num_categories = 2

	[feature.cvd_EMOT]
	type = "categorical"
	num_categories = 2

	[feature.cvd_HXHYPER]
	type = "categorical"
	num_categories = 2

	[feature.cvd_HXSTROKE]
	type = "categorical"
	num_categories = 2

	[feature.cvd_FOCLSYM]
	type = "categorical"
	num_categories = 2

	[feature.cvd_FOCLSIGN]
	type = "categorical"
	num_categories = 2

	[feature.cvd_HACHIN]
	type = "numerical"
	shape = [1]

	[feature.cvd_CVDCOG]
	type = "categorical"
	num_categories = 2

	[feature.cvd_STROKCOG]
	type = "categorical"
	num_categories = 2

	[feature.cvd_CVDIMAG]
	type = "categorical"
	num_categories = 2

	[feature.npiq_DEL]
	type = "categorical"
	num_categories = 4

	[feature.npiq_HALL]
	type = "categorical"
	num_categories = 4

	[feature.npiq_AGIT]
	type = "categorical"
	num_categories = 4

	[feature.npiq_DEPD]
	type = "categorical"
	num_categories = 4

	[feature.npiq_ANX]
	type = "categorical"
	num_categories = 4

	[feature.npiq_ELAT]
	type = "categorical"
	num_categories = 4

	[feature.npiq_APA]
	type = "categorical"
	num_categories = 4

	[feature.npiq_DISN]
	type = "categorical"
	num_categories = 4

	[feature.npiq_IRR]
	type = "categorical"
	num_categories = 4

	[feature.npiq_MOT]
	type = "categorical"
	num_categories = 4

	[feature.npiq_NITE]
	type = "categorical"
	num_categories = 4

	[feature.npiq_APP]
	type = "categorical"
	num_categories = 4

	[feature.gds_SATIS]
	type = "categorical"
	num_categories = 2

	[feature.gds_DROPACT]
	type = "categorical"
	num_categories = 2

	[feature.gds_EMPTY]
	type = "categorical"
	num_categories = 2

	[feature.gds_BORED]
	type = "categorical"
	num_categories = 2

	[feature.gds_SPIRITS]
	type = "categorical"
	num_categories = 2

	[feature.gds_AFRAID]
	type = "categorical"
	num_categories = 2

	[feature.gds_HAPPY]
	type = "categorical"
	num_categories = 2

	[feature.gds_HELPLESS]
	type = "categorical"
	num_categories = 2

	[feature.gds_STAYHOME]
	type = "categorical"
	num_categories = 2

	[feature.gds_MEMPROB]
	type = "categorical"
	num_categories = 2

	[feature.gds_WONDRFUL]
	type = "categorical"
	num_categories = 2

	[feature.gds_WRTHLESS]
	type = "categorical"
	num_categories = 2

	[feature.gds_ENERGY]
	type = "categorical"
	num_categories = 2

	[feature.gds_HOPELESS]
	type = "categorical"
	num_categories = 2

	[feature.gds_BETTER]
	type = "categorical"
	num_categories = 2

	[feature.faq_BILLS]
	type = "categorical"
	num_categories = 4

	[feature.faq_TAXES]
	type = "categorical"
	num_categories = 4

	[feature.faq_SHOPPING]
	type = "categorical"
	num_categories = 4

	[feature.faq_GAMES]
	type = "categorical"
	num_categories = 4

	[feature.faq_STOVE]
	type = "categorical"
	num_categories = 4

	[feature.faq_MEALPREP]
	type = "categorical"
	num_categories = 4

	[feature.faq_EVENTS]
	type = "categorical"
	num_categories = 4

	[feature.faq_PAYATTN]
	type = "categorical"
	num_categories = 4

	[feature.faq_REMDATES]
	type = "categorical"
	num_categories = 4

	[feature.faq_TRAVEL]
	type = "categorical"
	num_categories = 4

	[feature.bat_NACCMMSE]
	type = "numerical"
	shape = [1]

	[feature.bat_MOCATRAI]
	type = "categorical"
	num_categories = 2

	[feature.bat_MOCACUBE]
	type = "categorical"
	num_categories = 2

	[feature.bat_MOCACLOC]
	type = "categorical"
	num_categories = 2

	[feature.bat_MOCACLON]
	type = "categorical"
	num_categories = 2

	[feature.bat_MOCACLOH]
	type = "categorical"
	num_categories = 2

	[feature.bat_MOCANAMI]
	type = "numerical"
	shape = [1]

	[feature.bat_MOCADIGI]
	type = "categorical"
	num_categories = 3

	[feature.bat_MOCALETT]
	type = "categorical"
	num_categories = 2

	[feature.bat_MOCASER7]
	type = "numerical"
	shape = [1]

	[feature.bat_MOCAREPE]
	type = "categorical"
	num_categories = 3

	[feature.bat_MOCAFLUE]
	type = "categorical"
	num_categories = 2

	[feature.bat_MOCAABST]
	type = "categorical"
	num_categories = 3

	[feature.bat_MOCARECN]
	type = "numerical"
	shape = [1]

	[feature.bat_MOCAORDT]
	type = "categorical"
	num_categories = 2

	[feature.bat_MOCAORMO]
	type = "categorical"
	num_categories = 2

	[feature.bat_MOCAORYR]
	type = "categorical"
	num_categories = 2

	[feature.bat_MOCAORDY]
	type = "categorical"
	num_categories = 2

	[feature.bat_MOCAORPL]
	type = "categorical"
	num_categories = 2

	[feature.bat_MOCAORCT]
	type = "categorical"
	num_categories = 2

	[feature.bat_NACCMOCA]
	type = "numerical"
	shape = [1]

	[feature.cd_DIAGNOSIS]
	type = "categorical"
	num_categories = 3

	[feature.cdr_MEMORY]
	type = "numerical"
	shape = [1]

	[feature.cdr_ORIENT]
	type = "numerical"
	shape = [1]

	[feature.cdr_JUDGMENT]
	type = "numerical"
	shape = [1]

	[feature.cdr_COMMUN]
	type = "numerical"
	shape = [1]

	[feature.cdr_HOMEHOBB]
	type = "numerical"
	shape = [1]

	[feature.cdr_PERSCARE]
	type = "numerical"
	shape = [1]

	[feature.cdr_CDRSUM]
	type = "numerical"
	shape = [1]

	[feature.cdr_CDRGLOB]
	type = "numerical"
	shape = [1]

	[feature.FS_MTL_VOLUME]
	type = "numerical"
	shape = [1]

	[feature.FS_NEO-T_VOLUME]
	type = "numerical"
	shape = [1]

	[feature.FS_TEMPO_PARIETAL_VOLUME]
	type = "numerical"
	shape = [1]

	[feature.FS_FRONTAL_VOLUME]
	type = "numerical"
	shape = [1]

	[feature.gds_NACCGDS]
	type = "numerical"
	shape = [1]

	[feature.faq_FAQTOTAL]
	type = "numerical"
	shape = [1]

[labels]

	[label.amy_label]
	type = "categorical"
	num_categories = 2

	[label.tau_label]
	type = "categorical"
	num_categories = 2

